spring:
  datasource:
    # 데이터베이스 연결 URL (MySQL)
    url: jdbc:mysql://localhost:3306/kukokuk?serverTimezone=Asia/Seoul
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: kukokuk
    password: zxcv1234

  # Redis 기본 설정
  data:
    redis:
      host: localhost
      port: 6379

  # env 관련 설정 추가
  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

logging:
  level:
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO
      sqlonly: OFF
      sqltiming: INFO
      connection: OFF

    org:
      hibernate:
        # 하이버네이트 SQL 로그
        SQL: DEBUG

        type:
          descriptor:
            sql:
              # 바인딩 파라미터 추적 로그
              BasicBinder: TRACE

    # HikariCP 커넥션 풀 로그
    com.zaxxer.hikari: INFO

    # DataSource 관련 로그
    javax.sql.DataSource: OFF

# 파이썬 서버 경로 설정
pyserver:
  url: http://127.0.0.1:8000

gemini:
  api:
    key: ${GEMINI_API_KEY}
    baseUrl: https://generativelanguage.googleapis.com

# 임시 설정 : 수정필요
nhn:
  s3:
    tenant-id: AUTH_58a0a6438f054792b4338ed8b2440a82
    endpoint: https://kr1-api-object-storage.nhncloudservice.com
    access-key: ${OBJECT_STORAGE_ACCESS_KEY}
    secret-key: ${OBJECT_STORAGE_SECRET_KEY}
    bucket: kukokuk
    region-name: KR1